import type { FeedFixtureItem, TrackCandidate } from "@radar/core";

export const mockProviderFixture: {
  fixtureVersion: 1;
  candidates: TrackCandidate[];
  nextCursor: string;
} = {
  fixtureVersion: 1,
  nextCursor: "mock-cursor-2026-07-15T12:00:00Z",
  candidates: [
    {
      provider: "mock",
      externalReleaseId: "mock-release-glass-horizon",
      externalTrackId: "mock-track-glass-horizon-a",
      sourceLabel: "Spotify fixture",
      artistExternalId: "artist-lumen-field",
      artistName: "Lumen Field",
      title: "Glass Horizon",
      releaseTitle: "Glass Horizon",
      releaseType: "single",
      releaseDate: "2026-07-11",
      releaseDatePrecision: "day",
      firstSeenAt: "2026-07-12T09:00:00.000Z",
      credits: [{ name: "Lumen Field", role: "primary" }],
      durationMs: 218400,
      isrc: "USMCK2600001",
      region: "US",
      availability: "playable",
      providerUrl: "https://example.test/mock/spotify/glass-horizon",
      evidenceUrl: "https://example.test/mock/evidence/glass-horizon-a",
      evidenceType: "typed-mock-fixture",
      payloadHash: "sha256:glass-horizon-a",
    },
    {
      provider: "mock",
      externalReleaseId: "mock-release-glass-horizon-alt",
      externalTrackId: "mock-track-glass-horizon-b",
      sourceLabel: "Mock catalog fixture",
      artistExternalId: "artist-lumen-field",
      artistName: "Lumen Field",
      title: "Glass Horizon",
      releaseTitle: "Glass Horizon",
      releaseType: "single",
      releaseDate: "2026-07-11",
      releaseDatePrecision: "day",
      firstSeenAt: "2026-07-12T09:10:00.000Z",
      credits: [{ name: "Lumen Field", role: "primary" }],
      durationMs: 218900,
      isrc: "US-MCK-26-00001",
      region: "US",
      availability: "playable",
      providerUrl: "https://example.test/mock/catalog/glass-horizon",
      evidenceUrl: "https://example.test/mock/evidence/glass-horizon-b",
      evidenceType: "typed-mock-fixture",
      payloadHash: "sha256:glass-horizon-b",
    },
    {
      provider: "mock",
      externalReleaseId: "mock-release-static-bloom",
      externalTrackId: "mock-track-static-bloom-a",
      sourceLabel: "YouTube fixture",
      artistExternalId: "artist-oxide-echo",
      artistName: "Oxide Echo",
      title: "Static Bloom",
      releaseTitle: "Static Bloom",
      releaseType: "upload",
      releaseDate: "2026-07-09",
      releaseDatePrecision: "day",
      firstSeenAt: "2026-07-13T07:40:00.000Z",
      credits: [{ name: "Oxide Echo", role: "primary" }],
      durationMs: 194000,
      region: "US",
      availability: "playable",
      providerUrl: "https://example.test/mock/youtube/static-bloom",
      evidenceUrl: "https://example.test/mock/evidence/static-bloom-a",
      evidenceType: "typed-mock-fixture",
      payloadHash: "sha256:static-bloom-a",
    },
    {
      provider: "mock",
      externalReleaseId: "mock-release-static-bloom-ambiguous",
      externalTrackId: "mock-track-static-bloom-b",
      sourceLabel: "Mock upload fixture",
      artistExternalId: "artist-oxide-echo",
      artistName: "Oxide Echo",
      title: "Static Bloom",
      releaseTitle: "Static Bloom (session take)",
      releaseType: "upload",
      releaseDate: "2026-07-10",
      releaseDatePrecision: "day",
      firstSeenAt: "2026-07-13T08:00:00.000Z",
      credits: [{ name: "Oxide Echo", role: "primary" }],
      durationMs: 203000,
      region: "US",
      availability: "unavailable",
      providerUrl: "https://example.test/mock/upload/static-bloom-session",
      evidenceUrl: "https://example.test/mock/evidence/static-bloom-b",
      evidenceType: "typed-mock-fixture",
      payloadHash: "sha256:static-bloom-b",
    },
    {
      provider: "mock",
      externalReleaseId: "mock-release-afterimage",
      externalTrackId: "mock-track-afterimage",
      sourceLabel: "MusicBrainz fixture",
      artistExternalId: "artist-juniper-vale",
      artistName: "Juniper Vale",
      title: "Afterimage",
      releaseTitle: "Afterimage EP",
      releaseType: "ep",
      releaseDate: "2026-08-02",
      releaseDatePrecision: "day",
      firstSeenAt: "2026-07-14T16:20:00.000Z",
      credits: [{ name: "Juniper Vale", role: "primary" }],
      durationMs: 241000,
      region: "US",
      availability: "unavailable",
      providerUrl: "https://example.test/mock/musicbrainz/afterimage",
      evidenceUrl: "https://example.test/mock/evidence/afterimage",
      evidenceType: "typed-mock-fixture",
      payloadHash: "sha256:afterimage",
      isUpcoming: true,
    },
  ],
};

export const feedFixtures: FeedFixtureItem[] = [
  {
    id: "feed-1",
    state: "new",
    artist: "Lumen Field",
    title: "Glass Horizon",
    releaseTitle: "Glass Horizon",
    releaseType: "single",
    releaseDate: "2026-07-11",
    firstSeenAt: "2026-07-15T09:10:00.000Z",
    sources: [
      {
        provider: "Spotify fixture",
        href: "https://example.test/mock/spotify/glass-horizon",
        evidenceHref: "https://example.test/mock/evidence/glass-horizon-a",
      },
      {
        provider: "Mock catalog fixture",
        href: "https://example.test/mock/catalog/glass-horizon",
        evidenceHref: "https://example.test/mock/evidence/glass-horizon-b",
      },
    ],
    spotify: "playable",
    soundcloudState: "SEARCH_LINK_AVAILABLE",
    links: [
      { label: "Provider evidence", href: "https://example.test/mock/evidence/glass-horizon-a" },
    ],
    confidence: 1,
    matchReason: "Exact ISRC across two provider fixtures",
    region: "US",
    exportStatus: "eligible",
    accent: "coral",
  },
  {
    id: "feed-2",
    state: "needs_review",
    artist: "Oxide Echo",
    title: "Static Bloom",
    releaseTitle: "Static Bloom (session take)",
    releaseType: "upload",
    releaseDate: "2026-07-10",
    firstSeenAt: "2026-07-14T08:00:00.000Z",
    sources: [
      {
        provider: "Mock upload fixture",
        href: "https://example.test/mock/upload/static-bloom-session",
        evidenceHref: "https://example.test/mock/evidence/static-bloom-b",
      },
    ],
    spotify: "unavailable",
    soundcloudState: "SEARCH_LINK_AVAILABLE",
    links: [
      { label: "Source evidence", href: "https://example.test/mock/evidence/static-bloom-b" },
    ],
    confidence: 0.9,
    matchReason: "Title and artist agree; duration differs by 9 seconds",
    region: "US",
    exportStatus: "review_required",
    accent: "gold",
  },
  {
    id: "feed-3",
    state: "upcoming",
    artist: "Juniper Vale",
    title: "Afterimage",
    releaseTitle: "Afterimage EP",
    releaseType: "ep",
    releaseDate: "2026-08-02",
    firstSeenAt: "2026-07-13T16:20:00.000Z",
    sources: [
      {
        provider: "MusicBrainz fixture",
        href: "https://example.test/mock/musicbrainz/afterimage",
        evidenceHref: "https://example.test/mock/evidence/afterimage",
      },
    ],
    spotify: "unavailable",
    soundcloudState: "SEARCH_LINK_AVAILABLE",
    links: [
      { label: "Announcement evidence", href: "https://example.test/mock/evidence/afterimage" },
    ],
    confidence: 0.98,
    matchReason: "Exact mock release-group identifier",
    region: "US",
    exportStatus: "blocked",
    accent: "cyan",
  },
  {
    id: "feed-4",
    state: "saved",
    artist: "Mara Voss feat. Lumen Field",
    title: "Soft Collision",
    releaseTitle: "Soft Collision",
    releaseType: "feature",
    releaseDate: "2026-07-07",
    firstSeenAt: "2026-07-12T11:25:00.000Z",
    sources: [
      {
        provider: "Spotify fixture",
        href: "https://example.test/mock/spotify/soft-collision",
        evidenceHref: "https://example.test/mock/evidence/soft-collision",
      },
    ],
    spotify: "playable",
    soundcloudState: "SEARCH_LINK_AVAILABLE",
    links: [{ label: "Provider record", href: "https://example.test/mock/spotify/soft-collision" }],
    confidence: 1,
    matchReason: "Exact credited artist ID and ISRC",
    region: "US",
    exportStatus: "exported",
    accent: "lime",
  },
];

export const mockScanFeedFixture: FeedFixtureItem = {
  id: "feed-scan-1",
  state: "new",
  artist: "North Arcade",
  title: "Signal Fires",
  releaseTitle: "Signal Fires",
  releaseType: "single",
  releaseDate: "2026-07-15",
  firstSeenAt: "2026-07-15T12:00:00.000Z",
  sources: [
    {
      provider: "Mock provider",
      href: "https://example.test/mock/releases/signal-fires",
      evidenceHref: "https://example.test/mock/evidence/signal-fires",
    },
  ],
  spotify: "unavailable",
  soundcloudState: "SEARCH_LINK_AVAILABLE",
  links: [{ label: "Mock evidence", href: "https://example.test/mock/evidence/signal-fires" }],
  confidence: 1,
  matchReason: "New canonical release from the mock provider",
  region: "US",
  exportStatus: "blocked",
  accent: "coral",
};
